version: '3'

services:
  database:
    hostname: database.local
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres